[project]
name = "chatbot_invitro"
version = "0.1.0"
description = "sample chatbot app"
requires-python = ">=3.11"

dependencies = [
    "fastapi",
    "uvicorn",
    "psycopg2-binary",
    "requests",
    "numpy",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
seed="main.seed:main_seed_all"
seed_category="main.seed:main_seed_category"
seed_qa_original="main.seed:main_seed_qa_original"
seed_question_altered="main.seed:main_seed_question_altered"
debug = "main.debug:main"
debug_question = "main.debug_question:main"